//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBCE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fb2xsl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fb2xsl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MBCE.fb2xsl", typeof(fb2xsl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:fb=&quot;http://www.gribuser.ru/xml/fictionbook/2.0&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; encoding=&quot;UTF-8&quot;/&gt;
        ///	&lt;xsl:param name=&quot;src-name&quot; select=&quot;&apos;index.html&apos;&quot;/&gt;
        ///	&lt;xsl:key name=&quot;note-link&quot; match=&quot;fb:section&quot; use=&quot;@id&quot;/&gt;
        ///	&lt;xsl:template match=&quot;/*&quot;&gt;
        ///		&lt;!--&lt;!DOCTYPE ncx PUBLIC &quot;-//NISO//DTD ncx 2005-1//EN&quot; &quot;http://www.daisy.org/z3986/2005/ncx-2005-1.dtd&quot;&gt;--&gt;
        ///		&lt;ncx xmlns=&quot;http://www.daisy.org/z3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fb2_2_ncx {
            get {
                return ResourceManager.GetString("fb2_2_ncx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:fb=&quot;http://www.gribuser.ru/xml/fictionbook/2.0&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; &gt;
        ///	&lt;xsl:output encoding=&quot;UTF-8&quot; method=&quot;xml&quot;/&gt;
        ///	&lt;xsl:param name=&quot;saveimages&quot; select=&quot;2&quot;/&gt;
        ///	&lt;xsl:param name=&quot;tocdepth&quot; select=&quot;3&quot;/&gt;
        ///	&lt;xsl:param name=&quot;NotesTitle&quot; select=&quot;&apos;Сноски&apos;&quot;/&gt;
        ///	&lt;xsl:param name=&quot;src-name&quot; select=&quot;&apos;index.html&apos;&quot;/&gt;
        ///	&lt;xsl:param  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fb2_2_opf {
            get {
                return ResourceManager.GetString("fb2_2_opf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:fb=&quot;http://www.gribuser.ru/xml/fictionbook/2.0&quot;&gt;
        ///	&lt;xsl:output method=&quot;xml&quot; encoding=&quot;UTF-8&quot;/&gt;
        ///	&lt;xsl:key name=&quot;note-link&quot; match=&quot;fb:section&quot; use=&quot;@id&quot;/&gt;
        ///	&lt;xsl:template match=&quot;/*&quot;&gt;
        ///		&lt;html&gt;
        ///			&lt;head&gt;
        ///				&lt;meta HTTP-EQUIV=&quot;content-type&quot; CONTENT=&quot;text/html; charset=UTF-8&quot;/&gt;
        ///				&lt;title&gt;
        ///					&lt;xsl:value-of select=&quot;fb:description/fb:title-info/fb:book-title&quot;/&gt;
        ///				&lt;/title&gt;
        ///				&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fb2_2_xhtml {
            get {
                return ResourceManager.GetString("fb2_2_xhtml", resourceCulture);
            }
        }
    }
}
